# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
    ports:
      - 3308:3308  

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080